<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Marvel Guide Blog</title>
    <script src="https://kit.fontawesome.com/dfc0079155.js" crossorigin="anonymous"></script>
    <link rel="shortcut icon" type="image" href="https://e7.pngegg.com/pngimages/419/220/png-clipart-logo-marvel-comics-marvel-entertainment-marvel-studios-others-comics-avengers.png"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="Marvel Encyclopedia.css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bd-navbar bg-dark sticky-top">
    <div class="container-fluid">
    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Marvel_Logo.svg/1200px-Marvel_Logo.svg.png" alt="Logo" width="50" height="20" class="d-inline-block align-text-top">
    <a class="navbar-brand" href="Marvel Encyclopedia.html">Guide Blog</a>
    <button class="navbar-toggler"
            type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="fas fa-angle-double-down"></span>
    </button>
    <div class="collapse navbar-collapse"
            id="navbarSupportedContent">
      <ul class="navbar-nav  text-center me-auto ">
        <li class="nav-item">
          <a class="nav-link active"
             aria-current="page"
             href="Marvel Encyclopedia.html">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="movies.html">Movies</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="charachters.html">Characters</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="actors.html">Actors</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="news.html">News</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="merch.html">Merch</a>
        </li>
        <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
             <span class="position-absolute top start-100 translate-middle p-1 bg-danger border border-light rounded-circle">
     <span class="visually-hidden">New alerts</span>
   </span>
             Actions
           </a>
           <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
             <li><a class="dropdown-item" href="#">Profile</a></li>
             <li><a class="dropdown-item" href="#">Messages</a></li>
             <li><a class="dropdown-item" href="#">Forum</a></li>
           </ul>
         </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

        </div>
      </div>
    </nav>
<section>
  <div class="container-xxl">
    <div class="row align-items-center">
  <div class="row">
     <div class="col-lg-7">
       <h1 class="cen-word"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Marvel_Logo.svg/1200px-Marvel_Logo.svg.png" alt="Logo" width="200" height="80" <br> Guide Blog</h1>
       <p class="mainText">The Marvel Cinematic Universe (also known as MCU) is an American media franchise and shared universe centered on a series of superhero films produced by Marvel Studios. The films are based on characters that appear in American comic books published by Marvel Comics.</p>
     </div>
     <div class="col-lg-5 col-md-8 col-sm-10">
     </div>
   </div>
 </div>
</div>

</section>
<section class="karuselka">
  <div class="container-xxl">
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="row justify-content-between">
      <div class="col">
      <div class="card" style="width: 18rem;">
    <img src="https://i.pinimg.com/originals/54/95/fb/5495fbfee69d51e2322f28d3e19eaaa2.jpg" class="card-img-top" alt="movie">
    <div class="card-body">
      <h5 class="card-title">Movies</h5>
      <p class="card-text">Look up your favotite movies.</p>
      <a href="movies.html" class="btn btn-primary">Go to Movies</a>
    </div>
  </div>
    </div>
    <div class="col">
        <div class="col">
        <div class="card" style="width: 18rem;">
      <img src="https://cdn.vox-cdn.com/thumbor/ghi5BORR8MJ5WPosPUyAK2-sDW8=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/21882543/marvel_avengers_a_day_prologue.jpg" class="card-img-top" alt="characters">
      <div class="card-body">
        <h5 class="card-title">Characters</h5>
        <p class="card-text">Learn about your favotite characters.</p>
        <a href="charachters.html" class="btn btn-primary">Go to Characters</a>
      </div>
    </div>
      </div>
    </div>
    <div class="col">
      <div class="col">
        <div class="card" style="width: 18rem;">
      <img src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/chris-hemsworth-and-paul-rudd-attend-the-avengers-endgame-news-photo-1141734445-1555689033.jpg?crop=1.00xw:0.666xh;0,0.0974xh&resize=480:*" class="card-img-top" alt="actors">
      <div class="card-body">
        <h5 class="card-title">Actors</h5>
        <p class="card-text">Know your actors.</p>
        <a href="actors.html" class="btn btn-primary">Go to Actors</a>
      </div>
    </div>
      </div>
    </div>
  </div>
    </div>
    <div class="carousel-item">
      <div class="row justify-content-between">
      <div class="col">
      <div class="card" style="width: 18rem;">
    <img src="https://yt3.ggpht.com/fGvQjp1vAT1R4bAKTFLaSbdsfdYFDwAzVjeRVQeikH22bvHWsGULZdwIkpZXktcXZc5gFJuA3w=s900-c-k-c0x00ffffff-no-rj" class="card-img-top" alt="marvel">
    <div class="card-body">
      <h5 class="card-title">News</h5>
      <p class="card-text">Stay up to date with the latest news.</p>
      <a href="news.html" class="btn btn-primary">Go to News</a>
    </div>
  </div>
    </div>
    <div class="col">
        <div class="col">
        <div class="card" style="width: 18rem;">
      <img src="https://abgame.it/110948-large_default/pop-figure-marvel-merch-dr-strange.jpg" class="card-img-top" alt="characters">
      <div class="card-body">
        <h5 class="card-title">Merch</h5>
        <p class="card-text">Find something for you.</p>
        <a href="merch.html" class="btn btn-primary">Go to Mecrh</a>
      </div>
    </div>
      </div>
    </div>
    <div class="col">
      <div class="col">
      <div class="card" style="width: 18rem;">
    <img src="https://sportshub.cbsistatic.com/i/2021/03/17/0fea6014-5e2d-49ee-a03b-ba874d784336/mermaid-man-barnacle-boy-spongebob-squarepants-origin-1186404.jpg" class="card-img-top" alt="movie">
    <div class="card-body">
      <h5 class="card-title">It was DreamTeam</h5>
    </div>
  </div>
    </div>
    </div>
  </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
  </div>
</section>

    <div>
    <center>
    <h1 style="color:white;"> <hr><br>Please rate our site! </h1> <br>
    <form>
      <label for="bad"><input id="bad" type="radio" name="rating"> Bad</label>
          <label for="normal"><input id="normal" type="radio" name="rating"> Normal</label>
          <label for="good"><input id="good" type="radio" name="rating"> Good</label> <br> <br>
          <button type="submit">Submit</button> <br> <br>
        </form>
      </center>
    </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

